### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by seyfer** [dmaicher/underscore_issue_2852#1]
https://github.com/dmaicher/underscore_issue_2852/blob/348eef226ec7392b2ced2b92ddf2fcba2517ab5c/index.js#L9

You might want to use https://lodash.com/docs/4.17.11#camelCase instead? :)

**Comment by dmaicher** [comment]
Haha I could but `underscore.string` also provides it :wink: See https://github.com/jashkenas/underscore/issues/2852
